name: Trigger docs build
on:
  push:
  schedule:
    - "0 0 * * 1"
jobs:
  trigger:
    name: Trigger webhook
    runs-on: ubuntu-22.04
    env:
      readthedocs_token: ${{ secrets.readthedocs_token }}
    steps:
      - if: ${{ env.readthedocs_token != '' }}
        run: |
          curl -s -X POST \
            -d "branches=${{ github.ref_name }}" \
            -d "token=${{ env.readthedocs_token }}" \
            https://readthedocs.org/api/v2/webhook/nethserver-devel/49560/
